name: Variable
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Jayaramachandran <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  http: ^0.12.0+1
